[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-coach"
version = "0.1.0"

[tool.setuptools.packages.find]
where=["."]
include=["my_coach*"]

